dist: trusty
sudo: required
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
before_install:
  - npm install -g yarn
script:
  - yarn lint
  - yarn test
notifications:
  email:
    - dev-support@ampleforth.org
  slack: fragmentsorg:2bN0L0FCZZ0illBRyPucRZkV
